### ISSUE TITLE
Factory parameter types unnecessarily require registration

### ISSUE THREAD

**Issue by paulspiteri** [ZachBray/eye-oh-see#5]
This is a problem when the type in question is from a library and can't be changed to add a decorator.

Uncaught TypeError
    at Object.getOwnMetadata (http://localhost:3000/scripts/vendor.js:66412:19)
    at Function.RegistrationMetadata.findOrCreate (http://localhost:3000/scripts/vendor.js:16971:40)
    at Container.register (http://localhost:3000/scripts/vendor.js:88242:55)
    at http://localhost:3000/scripts/vendor.js:53070:23
    at Array.forEach (native)
    at StompClientProviderImpl.createStompClientWrapper (http://localhost:3000/scripts/vendor.js:53068:18)
    at StompClientProviderImpl.getClient (http://localhost:3000/scripts/main.bundle.js:1192:44)
    at StompClientProviderImpl.onStartup (http://localhost:3000/scripts/main.bundle.js:1185:27)
    at http://localhost:3000/scripts/main.bundle.js:3647:71
    at Array.forEach (native)

**Comment by ZachBray** [comment]
Investigating this it looks like the "key" that is being used to register the instance against isn't an object or function type:

https://github.com/rbuckton/reflect-metadata/blob/master/Reflect.ts#L805

It may be the case that you have the typings for an external dependency installed but the implementation is never imported so the reference is null?

https://github.com/rbuckton/reflect-metadata/blob/master/Reflect.ts#L1279

**Comment by paulspiteri** [comment]
Re-visited this....
now getting:


	TypeError: Cannot read property 'ioc:metadata' of undefined
    at Registration.protectAgainstCycles (http://localhost:3000/vendor.dll.js:93079:1
